version: "3.8"

services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancy
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build:
      context: ./backend/go
    volumes:
      - ./backend/go:/app
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=secret
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=balancy
    command: [ "/go/bin/air" ]
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/web
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
