version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80" # Porta do React para o host
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "8080:8080" # Porta do Go server para o host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
