version: '3.8'

services:
  app:
    build:
      context: .  # Diretório de contexto para o Dockerfile
    ports:
      - "3000:80"   # Mapeia a porta 3000 do contêiner para a 3000 no host (React)
      - "8080:8080"   # Mapeia a porta 8080 do contêiner para a 8080 no host (Go server)
    env_file:
      - ./server/.env # Monta o arquivo .env no contêiner
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
